FROM quay.io/libpod/alpine:latest

RUN apk add --no-cache curl \
    && curl https://frankenphp.dev/install.sh | sh \
    && mv frankenphp /usr/local/bin/

RUN rm -rf /var/cache/apk/*

RUN mkdir /var/www
WORKDIR /var/www

EXPOSE 80

# CMD ["frankenphp", "serve"]